CLIENT_SERVER_BIND_PORT: 8000
TRACKER_PORT: 5000
TRACKER_HOST: '127.0.0.1'
CLIENT_TRACKER_BIND_PORT: 8000
TEMP_DIR: './distributed_downloader_client_temp'
THREADS: 4
PROXY:
  HTTP:
  HTTPS:
DOWNLOAD_DIR: './downloads'
