TO_CLIENT_PORT: 8000
MANAGER_PORT: 5000
MANAGER_ADDR_IPV4: '192.168.50.43'
TO_MANAGER_PORT: 6000
TMP_DIR: './ddr-download/server/tmp/'
THREADS_NUM: 16
PROXIES:
  HTTP:
  HTTPS:
TARGET_DIR: './ddr-download/server/target/'
